/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chuhoodgym_manager;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tran Nhan Nghia
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
        //set full screen
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        //Load du lieu len bang
        loadInfoEmployee();
        
        //Set auto ID
        setID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        rdbNam = new javax.swing.JRadioButton();
        rdbNu = new javax.swing.JRadioButton();
        spnDOB = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        cmbWork = new javax.swing.JComboBox<>();
        spnDateWorking = new javax.swing.JSpinner();
        txtAllowance = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        txtFind = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmbArrangement = new javax.swing.JComboBox<>();
        txtTotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblEmployee.setFocusable(false);
        tblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmployee);

        jLabel1.setText("ID");

        txtID.setFocusable(false);

        jLabel2.setText("Name");

        jLabel3.setText("Sex");

        jLabel4.setText("DOB");

        jLabel5.setText("Address");

        buttonGroup1.add(rdbNam);
        rdbNam.setText("Nam");
        rdbNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbNamActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbNu);
        rdbNu.setText("Nu");
        rdbNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbNuActionPerformed(evt);
            }
        });

        spnDOB.setModel(new javax.swing.SpinnerDateModel());
        spnDOB.setEditor(new javax.swing.JSpinner.DateEditor(spnDOB, "dd/MM/YYYY"));

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane2.setViewportView(txtAddress);

        jLabel6.setText("Phone Number");

        jLabel11.setText("Email");

        jLabel8.setText("Work");

        jLabel9.setText("Start Working Date");

        jLabel10.setText("Allowance");

        cmbWork.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quan ly", "PT", "Tap vu", "Bao ve" }));

        spnDateWorking.setModel(new javax.swing.SpinnerDateModel());
        spnDateWorking.setEditor(new javax.swing.JSpinner.DateEditor(spnDateWorking, "dd/MM/YYYY"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtID)
                    .addComponent(txtName)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rdbNam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(rdbNu)
                        .addGap(24, 24, 24))
                    .addComponent(spnDOB)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbWork, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(spnDateWorking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtID)
                    .addComponent(jLabel6)
                    .addComponent(txtPhoneNumber))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName)
                    .addComponent(jLabel11)
                    .addComponent(txtEmail))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbNam)
                    .addComponent(rdbNu)
                    .addComponent(jLabel8)
                    .addComponent(cmbWork))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spnDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(spnDateWorking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(122, 122, 122))))))
        );

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnModify.setText("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        txtFind.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFindMouseClicked(evt);
            }
        });

        btnFind.setText("Find");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        jLabel7.setText("Sap xep");

        cmbArrangement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*", "Quan ly", "PT", "Tap vu", "Bao ve" }));
        cmbArrangement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbArrangementActionPerformed(evt);
            }
        });

        txtTotal.setFocusable(false);

        jLabel12.setText("Total");

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\icons8-back-to-50 (1).png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1869, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClear)
                            .addComponent(btnModify)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAdd)
                                    .addComponent(btnDel))
                                .addGap(193, 193, 193)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbArrangement, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnFind)))))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel14)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(cmbArrangement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFind))
                        .addGap(26, 26, 26)
                        .addComponent(btnDel)
                        .addGap(27, 27, 27)
                        .addComponent(btnClear)
                        .addGap(18, 18, 18)
                        .addComponent(btnModify)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadInfoEmployee(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String dbURL="jdbc:sqlserver://MSI\\SQLEXPRESS:1433; databaseName=ChuhoodGym; user=test; password=1234567890"; 
            String query="SELECT E.ID_Employee,E.Name_Employee,E.Sex,E.DOB,E.Emp_Address,E.Phone_Number,E.Email,W.Title_Work,E.Start_Working_Day,E.Allowance FROM Employee E JOIN Work W ON E.ID_Work=W.ID_Work;";
            Connection con=DriverManager.getConnection(dbURL);
            PreparedStatement ps=con.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel m=new DefaultTableModel(new Object[]{"ID","Name", "Sex", "DOB", "Address","Phone Number","Email","Work","Start Working Date","Allowance"}, 0);
               tblEmployee.setModel(m);
            while (rs.next()) {
                ((DefaultTableModel)tblEmployee.getModel()).addRow(new Object[]{
                    rs.getString(1), 
                    rs.getString(2), 
                    rs.getString(3), 
                    rs.getDate(4), 
                    rs.getString(5),
                    rs.getString(6),
                    rs.getString(7),
                    rs.getString(8),
                    rs.getDate(9),
                    rs.getInt(10),
                }); 
            }
            
        }catch(Exception ex){
            System.out.println(ex);
        }
        
        //set Total Employee
        setTotal();
    }
    
    private void setTotal(){
        int sum=0;
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String dbURL="jdbc:sqlserver://MSI\\SQLEXPRESS:1433; databaseName=ChuhoodGym; user=test; password=1234567890"; 
            String query="SELECT COUNT(*) AS SUM_Emp FROM Employee;";
            Connection connector=DriverManager.getConnection(dbURL);
            PreparedStatement ps=connector.prepareStatement(query);
            ResultSet sum_Emp=ps.executeQuery();
            while(sum_Emp.next()){
                sum=sum_Emp.getInt("SUM_Emp");
            }
        }catch(Exception ex){
            sum=0;
        }
        txtTotal.setText(String.valueOf(sum));
    }
    
        private void setTotalFollowTypeWork(String typeWork){
        int sum=0;
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String dbURL="jdbc:sqlserver://MSI\\SQLEXPRESS:1433; databaseName=ChuhoodGym; user=test; password=1234567890"; 
            String query="SELECT COUNT(*) AS SUM_Emp FROM Employee E JOIN Work W ON E.ID_Work=W.ID_Work WHERE W.Title_Work=?;";
            Connection connector=DriverManager.getConnection(dbURL);
            PreparedStatement ps=connector.prepareStatement(query);
            ps.setString(1, typeWork);
            ResultSet sum_Emp=ps.executeQuery();
            while(sum_Emp.next()){
                sum=sum_Emp.getInt("SUM_Emp");
            }
        }catch(Exception ex){
            sum=0;
        }
        txtTotal.setText(String.valueOf(sum));
    }
    
    private void setID(){
        String id=null;
        String ancestors; //Tien to E
        int numberID; //so duoi 00x || 0xx
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String dbURL="jdbc:sqlserver://MSI\\SQLEXPRESS:1433; databaseName=ChuhoodGym; user=test; password=1234567890"; 
            String query="SELECT MAX(ID_Employee) AS MAX_ID FROM Employee;";
            Connection connector=DriverManager.getConnection(dbURL);
            PreparedStatement ps=connector.prepareStatement(query);
            ResultSet rs_STT=ps.executeQuery();
            while(rs_STT.next()){
                id=rs_STT.getString("MAX_ID");
            }
        }catch(Exception ex){
            numberID=0;
        }
        
        ancestors=id.substring(0, 1); //E
        numberID=Integer.valueOf(id.substring(1, 4)); //number
        
        if(numberID<9) txtID.setText(ancestors +"00"+ String.valueOf(numberID+1));
        else if(numberID<99) txtID.setText(ancestors +"0"+ String.valueOf(numberID+1));
        else txtID.setText(ancestors + String.valueOf(numberID+1));
    }
    
    private boolean confirmInfoEmployee(){
        boolean check=true;
        if(txtName.getText().equals("")==true || txtPhoneNumber.getText().equals("")==true 
                || cmbWork.getItemAt(cmbWork.getSelectedIndex()).equals("")==true){
            JOptionPane.showMessageDialog(rootPane, "Phai nhap day du cac thong tin co ban nhu: Ten, So dien thoai va Loai cong viec");
            check=false;
        }
        return check;
    }
    
    //Get ID Work from Title Work
    private String getIDWork(){
        String id=null;
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String dbURL="jdbc:sqlserver://MSI\\SQLEXPRESS:1433; databaseName=ChuhoodGym; user=test; password=1234567890"; 
            String query="SELECT ID_Work FROM Work WHERE Title_Work=?;";
            Connection connector=DriverManager.getConnection(dbURL);
            PreparedStatement ps=connector.prepareStatement(query);
            ps.setString(1, cmbWork.getItemAt(cmbWork.getSelectedIndex()));
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                id=rs.getString("ID_Work");
            }
        }catch(Exception ex){
            System.out.println(ex);
        }
        return id; 
    }
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if(confirmInfoEmployee()==true){
            String query="INSERT INTO Employee VALUES(?,?,?,?,?,?,?,?,?,?);";
            String id=txtID.getText();
            String name=txtName.getText();
            String sex=gioiTinh;
            String dob=new SimpleDateFormat("yyyy-MM-dd").format(spnDOB.getValue());
            String address=txtAddress.getText();
            String phoneNumber=txtPhoneNumber.getText();
            String email=txtEmail.getText();
            String idWork=getIDWork();
            String startWorkingDate=new SimpleDateFormat("yyyy-MM-dd").format(spnDateWorking.getValue());
            int allowance=Integer.valueOf(txtAllowance.getText());
            
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String dbURL="jdbc:sqlserver://MSI\\SQLEXPRESS:1433; databaseName=ChuhoodGym; user=test; password=1234567890"; 
                Connection con=DriverManager.getConnection(dbURL);
                PreparedStatement ps=con.prepareStatement(query);
                ps.setString(1, id);
                ps.setString(2, name);
                ps.setString(3, sex);
                ps.setString(4, dob);
                ps.setString(5, address);
                ps.setString(6, phoneNumber);
                ps.setString(7, email);
                ps.setString(8, idWork);
                ps.setString(9, startWorkingDate);
                ps.setInt(10, allowance);
                
                ps.executeUpdate();
            }catch(Exception ex){
                System.out.println(ex);
            }
            btnClearActionPerformed(evt);
            loadInfoEmployee();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private String gioiTinh;
    private void rdbNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbNamActionPerformed
        gioiTinh="Nam";
    }//GEN-LAST:event_rdbNamActionPerformed

    private void rdbNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbNuActionPerformed
        gioiTinh="Nu";
    }//GEN-LAST:event_rdbNuActionPerformed

    Calendar cal=Calendar.getInstance();
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        setID();
        txtName.setText("");
        rdbNam.setSelected(true);
        spnDOB.setValue(cal.getTime());
        txtAddress.setText("");
        txtPhoneNumber.setText("");
        txtEmail.setText("");
        cmbWork.setSelectedIndex(0);
        spnDateWorking.setValue(cal.getTime());
        txtAllowance.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void tblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeMouseClicked
        int selectedIndex=tblEmployee.getSelectedRow();
        txtID.setText(tblEmployee.getValueAt(selectedIndex, 0)+"");
        txtName.setText(tblEmployee.getValueAt(selectedIndex, 1)+"");
        
        if(tblEmployee.getValueAt(selectedIndex, 2).equals("Nam"))
            rdbNam.setSelected(true);
        else rdbNu.setSelected(true);
        

//        spnDOB.setValue(tblEmployee.getValueAt(selectedIndex, 3)+"");
//        System.out.println(tblEmployee.getValueAt(selectedIndex, 3));
//        System.out.println(cal.getTime());
        //spnDOB.setValue(cal.getTime());
        
        txtAddress.setText(tblEmployee.getValueAt(selectedIndex, 4)+"");
        txtPhoneNumber.setText(tblEmployee.getValueAt(selectedIndex, 5)+"");
        txtEmail.setText(tblEmployee.getValueAt(selectedIndex, 6)+"");
        cmbWork.setSelectedItem(tblEmployee.getValueAt(selectedIndex, 7)+"");
        
        txtAllowance.setText(tblEmployee.getValueAt(selectedIndex, 9)+"");
    }//GEN-LAST:event_tblEmployeeMouseClicked

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        String id=txtID.getText();
        String name=txtName.getText();
        int confirm=JOptionPane.showConfirmDialog(rootPane, "Ban co chac muon xoa "+name+" khoi danh sach khong?","",JOptionPane.YES_NO_OPTION);
        if(confirm== JOptionPane.YES_OPTION){
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String dbURL="jdbc:sqlserver://MSI\\SQLEXPRESS:1433; databaseName=ChuhoodGym; user=test; password=1234567890"; 
                String query="DELETE Employee WHERE ID_Employee=? AND Name_Employee=?;";
                Connection con=DriverManager.getConnection(dbURL);
                PreparedStatement ps=con.prepareStatement(query);
                ps.setString(1, id);
                ps.setString(2, name);

                ps.executeUpdate();
            }catch(Exception ex){
                System.out.println(ex);
            }
            btnClearActionPerformed(evt);
            loadInfoEmployee();
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        String id=txtID.getText();
        String name=txtName.getText();
        String sex=gioiTinh;
        String dob=new SimpleDateFormat("yyyy-MM-dd").format(spnDOB.getValue());
        String address=txtAddress.getText();
        String phoneNumber=txtPhoneNumber.getText();
        String email=txtEmail.getText();
        String idWork=getIDWork();
        String startWorkingDate=new SimpleDateFormat("yyyy-MM-dd").format(spnDateWorking.getValue());
        int allowance=Integer.valueOf(txtAllowance.getText());
        
        int confirm=JOptionPane.showConfirmDialog(rootPane, "Ban co chac muon chinh sua thong tin khong?","",JOptionPane.YES_NO_OPTION);
        if(confirm== JOptionPane.YES_OPTION){
            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String dbURL="jdbc:sqlserver://MSI\\SQLEXPRESS:1433; databaseName=ChuhoodGym; user=test; password=1234567890"; 
                String query="UPDATE Employee SET Name_Employee=?, Sex=?,DOB=?,Emp_Address=?,Phone_Number=?,Email=?,ID_Work=?,Start_Working_Day=?, Allowance=? WHERE ID_Employee=?; ";
                Connection con=DriverManager.getConnection(dbURL);
                PreparedStatement ps=con.prepareStatement(query);
                
                ps.setString(1, name);
                ps.setString(2, sex);
                ps.setString(3, dob);
                ps.setString(4, address);
                ps.setString(5, phoneNumber);
                ps.setString(6, email);
                ps.setString(7, idWork);
                ps.setString(8, startWorkingDate);
                ps.setInt(9, allowance);
                ps.setString(10, id);

                ps.executeUpdate();
            }catch(Exception ex){
                System.out.println(ex);
            }
            btnClearActionPerformed(evt);
            loadInfoEmployee();
        } 
    }//GEN-LAST:event_btnModifyActionPerformed

    private void cmbArrangementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbArrangementActionPerformed
        String arrangementWork=cmbArrangement.getItemAt(cmbArrangement.getSelectedIndex());
        if(arrangementWork.equals("*")==true){
            loadInfoEmployee();
            setTotal();
        }
        else{
            try{
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String dbURL="jdbc:sqlserver://MSI\\SQLEXPRESS:1433; databaseName=ChuhoodGym; user=test; password=1234567890"; 
                String query="SELECT E.ID_Employee,E.Name_Employee,E.Sex,E.DOB,E.Emp_Address,E.Phone_Number,E.Email,W.Title_Work,E.Start_Working_Day,E.Allowance FROM Employee E JOIN Work W ON E.ID_Work=W.ID_Work WHERE W.Title_Work=?;";
                Connection con=DriverManager.getConnection(dbURL);
                PreparedStatement ps=con.prepareStatement(query);
                ps.setString(1, arrangementWork);

                ResultSet rs = ps.executeQuery();
                DefaultTableModel m=new DefaultTableModel(new Object[]{"ID","Name", "Sex", "DOB", "Address","Phone Number","Email","Work","Start Working Date","Allowance"}, 0);
                   tblEmployee.setModel(m);
                while (rs.next()) {
                    ((DefaultTableModel)tblEmployee.getModel()).addRow(new Object[]{
                        rs.getString(1), 
                        rs.getString(2), 
                        rs.getString(3), 
                        rs.getDate(4), 
                        rs.getString(5),
                        rs.getString(6),
                        rs.getString(7),
                        rs.getString(8),
                        rs.getDate(9),
                        rs.getInt(10),
                    }); 
                }

            }catch(Exception ex){
                System.out.println(ex);
            }
            //Dem so luong nhan vien
            setTotalFollowTypeWork(arrangementWork);
        }
    }//GEN-LAST:event_cmbArrangementActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String idFinder=txtFind.getText();
        if(idFinder.equals("")==false){
            try{
                int numberID=Integer.valueOf(idFinder.substring(1, 4)); //number
                int indexCurrentRow=numberID-1;
                tblEmployee.getSelectionModel().addSelectionInterval(indexCurrentRow,indexCurrentRow);
                //tblEmployee.selectAll(); Lay toan bo
               
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(rootPane, "Ma nhan vien co dinh dang Exxx");
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Ban chua nhap thong tin tim kiem");
        } 
    }//GEN-LAST:event_btnFindActionPerformed

    private void txtFindMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFindMouseClicked
        loadInfoEmployee();
    }//GEN-LAST:event_txtFindMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnModify;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbArrangement;
    private javax.swing.JComboBox<String> cmbWork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdbNam;
    private javax.swing.JRadioButton rdbNu;
    private javax.swing.JSpinner spnDOB;
    private javax.swing.JSpinner spnDateWorking;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAllowance;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
