/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chuhoodgym_manager;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Tran Nhan Nghia
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
        txtUserName.setBackground(new Color(0,0,0,0));
        txtPassword.setBackground(new Color(0,0,0,0));  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        ckbShowPassword = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JLabel();
        btnCancel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 340, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Copyright © 2021 • All rights reserved");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 860, -1, -1));

        txtUserName.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(255, 255, 255));
        txtUserName.setBorder(null);
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 460, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 460, 30));

        txtPassword.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 490, 460, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 520, 460, 30));

        ckbShowPassword.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ckbShowPassword.setForeground(new java.awt.Color(255, 255, 255));
        ckbShowPassword.setText("Show Password");
        ckbShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckbShowPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(ckbShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, -1, -1));

        jLabel9.setFont(new java.awt.Font("UTM Gradoo", 1, 65)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Chuhood.Gym");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, -1, -1));

        btnLogin.setIcon(new javax.swing.ImageIcon("F:\\Programming\\App\\ChuhoodGym\\photo\\buttonLogin.png")); // NOI18N
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 640, -1, -1));

        btnCancel.setIcon(new javax.swing.ImageIcon("F:\\Programming\\App\\ChuhoodGym\\photo\\buttonCancel.png")); // NOI18N
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 640, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("F:\\Programming\\App\\ChuhoodGym\\photo\\gymLogin3.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("F:\\Programming\\App\\ChuhoodGym\\photo\\gymLogin1.png")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Kiem tra thong tin nhap day du hay ko
    private boolean confirmInfo(){
        boolean check=true;
        if(txtPassword.getPassword().length==0){
            JOptionPane.showMessageDialog(rootPane, "Chua nhap password");
            check=false;
        }
        else if(txtUserName.getText().equals("")==true){
            JOptionPane.showMessageDialog(rootPane, "Chua nhap username");
            check=false;
        }
        return check;
    }
    
    //Gia ma mat khau
    private boolean decodePassword(String passwordFromDatabase){
        boolean checkPass=true;
        char[] passWordFromInput=txtPassword.getPassword(); //Mat khau bi ma hoa lay tu form
        char[] passWordFormDatabaseToChar = passwordFromDatabase.toCharArray(); //Mat khau bi ma hoa lay tu database chuyen sang char
        
        if (passWordFromInput.length != passWordFormDatabaseToChar.length) {
            checkPass = false;
        } else {
            checkPass = Arrays.equals (passWordFromInput, passWordFormDatabaseToChar);
        }
        
        //Zero out the password.
        Arrays.fill(passWordFormDatabaseToChar,'0');

        return checkPass;
    }
    
    private String getPassword; //Lay password dung 
    //Lay password tu csdl sau khi nhap username va kiem tra mat khau co dung hay khong
    private boolean isPasswordCorrect() {
        boolean isCorrect = true;
        String userName=txtUserName.getText();
        String passwordFromDatabase=null;
        try{
            String queryFindPass="SELECT Password FROM Account WHERE Username=?;";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String dbURL="jdbc:sqlserver://MSI\\SQLEXPRESS:1433; databaseName=ChuhoodGym; user=test; password=1234567890"; 
            Connection con=DriverManager.getConnection(dbURL);
            PreparedStatement ps=con.prepareStatement(queryFindPass);
            ps.setString(1, userName);
            ResultSet rs=ps.executeQuery();
            
            //Co Bug: Neu nhap khong dung username thi resultset se rong
            
            while(rs.next())
                passwordFromDatabase=rs.getString("Password");
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
        getPassword=passwordFromDatabase;
        
        //Giai ma password va kiem tra
        if(decodePassword(passwordFromDatabase)==false){
            isCorrect = false;
            JOptionPane.showMessageDialog(rootPane, "Sai mat khau");
        }
        //else JOptionPane.showMessageDialog(rootPane, "Mat khau hop le");
    
    return isCorrect;
}
    
//   checkBox.addActionListener(new ActionListener() {
//   public void actionPerformed(ActionEvent e) {
    private void showPass(){
        if(ckbShowPassword.isSelected()){
            txtPassword.setText(getPassword);
            System.out.print(getPassword);
        }
        else{
            txtPassword.setEchoChar('*');
        }
    }
    
    
    public String userNameLogin;
    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        String titleWork = null;
        if(confirmInfo()==true){
            if(isPasswordCorrect()==true){
                //Xu ly kiem tra neu nguoi dung dang nhap user va pass chinh xac la admin thi moi login vao
                //Con khong phai thi khong vao duoc
                
                String query="SELECT W.Title_Work FROM Employee E JOIN Account A ON E.ID_Employee=A.ID_Employee "
                    + "JOIN Work W ON E.ID_Work=W.ID_Work WHERE A.Username=? AND A.Password=?;";
                String userName=txtUserName.getText();
                String inputPasswordToDatabase = getPassword;
                try{
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    String dbURL="jdbc:sqlserver://MSI\\SQLEXPRESS:1433; databaseName=ChuhoodGym; user=test; password=1234567890"; 
                    Connection con=DriverManager.getConnection(dbURL);
                    PreparedStatement ps=con.prepareStatement(query);
                    ps.setString(1, userName);
                    ps.setString(2,inputPasswordToDatabase);
                    userNameLogin=userName; //Lay ten username
                    
                    ResultSet rs=ps.executeQuery();
                    if(rs!=null){
                        while(rs.next())
                            titleWork=rs.getString("Title_Work");
                    }
                    else JOptionPane.showMessageDialog(rootPane, "Tai khoan khong ton tai");
                }catch(Exception ex){
                    System.out.println(ex);
                }
                if(titleWork.equals("Quan ly")==true){
                    System.out.println(userNameLogin);
                    DashBoard db=new DashBoard();
                    db.setVisible(true);
                    this.setVisible(false);
                }
                    
                else JOptionPane.showMessageDialog(rootPane, "Ban khong phai admin");
            }
        }
        else JOptionPane.showMessageDialog(rootPane, "Dang nhap Khong Thanh Cong");
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCancelMouseClicked

    private void ckbShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckbShowPasswordMouseClicked
        if(ckbShowPassword.isSelected()){
            txtPassword.setEchoChar((char)0);
        }
        else{
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_ckbShowPasswordMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCancel;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JCheckBox ckbShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
